import { EventName } from "../types/analytics";

export const ANALYTICS_EVENTS: Record<string, EventName> = {
  PAGE_VIEW: 'page_view',
  QUIZ_DETAIL_VIEW: 'quiz_detail_view',
  RESULT_FREE_VIEW: 'result_free_view',
  REPORT_FULL_VIEW: 'report_full_view',
  HISTORY_VIEW: 'history_view',
  MEMBER_CENTER_VIEW: 'member_center_view',
  QUIZ_CLICK: 'quiz_click',
  QUIZ_START: 'quiz_start',
  QUIZ_ANSWER: 'quiz_answer',
  QUIZ_COMPLETE: 'quiz_complete',
  QUIZ_EXIT: 'quiz_exit',
  PAYWALL_VIEW: 'paywall_view',
  UNLOCK_CLICK: 'unlock_click',
  PURCHASE_CLICK: 'purchase_click',
  PAYMENT_INITIATE: 'payment_initiate',
  PAYMENT_SUCCESS: 'payment_success',
  PAYMENT_FAIL: 'payment_fail',
  PAYMENT_CANCEL: 'payment_cancel',
  MEMBER_ACTIVATE: 'member_activate',
  MEMBER_BENEFIT_USE: 'member_benefit_use',
  REGISTER_SUCCESS: 'register_success',
  LOGIN_SUCCESS: 'login_success',
  ACCOUNT_BIND_SUCCESS: 'account_bind_success',
  RESTORE_PURCHASE: 'restore_purchase',
  LOGOUT: 'logout',
  SHARE_CLICK: 'share_click',
  SHARE_SUCCESS: 'share_success',
  RELATED_QUIZ_CLICK: 'related_quiz_click',
};
